# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation

book_list:
    path:      /
    methods: [GET]
    defaults:  { _controller: AppBundle:Books:index }

book_add:
    path:      /book/add
    methods: [POST]
    defaults:  { _controller: AppBundle:Books:add }